### ISSUE TITLE
Regression après avoir updaté le contenu HTML W3C

### ISSUE THREAD

**Issue by Harrylepap** [Harrylepap/something#18]
![image](https://user-images.githubusercontent.com/17026924/157180168-efe7da39-a5ec-4922-9283-54ac03f4d295.png)
Veuillez régler cette barre gris

**Comment by Anjaraniaina** [comment]
Bonjour, @Harrylepap 
Je ne trouve pas le bug

**Comment by Harrylepap** [comment]
est-ce que tu es sur la branche dev ?

**Comment by Anjaraniaina** [comment]
@Harrylepap 
Oui, mais il n' y a vraiment pas de  barre gris
