### ISSUE TITLE
Afficher la liste de tous les contributeurs dans le README.md

### ISSUE THREAD

**Issue by Harrylepap** [Harrylepap/something#30]
Il y a une fonction de github qui permet d'afficher la liste des personnes qui ont contribué au projet.

**Comment by NyAndoMayah** [comment]
Pour cela il faudrait mettre git log pour voir la liste et mettre git log -p pour plus de détails .

**Comment by NyAndoMayah** [comment]
Cette fonction va permettre de voir tous les commits avec l'auteur de ce commit donc également ceux qui contribuent au projet

**Comment by Harrylepap** [comment]
Non, ce n'est pas comme ca. Regarde sur github sur comment afficher la liste des contributeurs dans les readme

**Comment by NyAndoMayah** [comment]
Afin d'installer remark-contributor, il suffira d'écrire dans node.js:
> npm install remark-git-contributors

Puis, ouvrir le readme.md et écrire dedans le titre **## Contributors** 
Ensuite il nous faudra avoir un module par exemple readme.js dans lequel il y aura le code ci-dessous:
_

> import {read} from 'to-vfile'
> import {remark} from 'remark'
> import remarkGfm from 'remark-gfm'
> import remarkGitContributors from 'remark-git-contributors'
> 
> main()
> 
> async function main() {
>   const file = await remark()
>     .use(remarkGfm) // Required: add support for tables (a GFM feature).
>     .use(remarkGitContributors)
>     .process(await read('example.md'))
> 
>   console.log(String(file))
> }

_
Enfin il faut exécuter node readme.js et il y aura un tableau avec la liste de tous les contributeurs :) .

**Comment by NyAndoMayah** [comment]
Afin d'installer remark-contributor, il suffira d'écrire dans node.js:

npm install remark-git-contributors

Puis, ouvrir le readme.md et écrire dedans le titre ## Contributors
Ensuite il nous faudra avoir un module par exemple readme.js dans lequel il y aura le code ci-dessous:
_

import {read} from 'to-vfile'
import {remark} from 'remark'
import remarkGfm from 'remark-gfm'
import remarkGitContributors from 'remark-git-contributors'

main()

async function main() {
const file = await remark()
.use(remarkGfm) // Required: add support for tables (a GFM feature).
.use(remarkGitContributors)
.process(await read('readme.md'))

console.log(String(file))
}

_
Enfin il faut exécuter node readme.js et il y aura un tableau avec la liste de tous les contributeurs :) .

**Comment by NyAndoMayah** [comment]
Afin d'installer remark-contributor, il suffira d'écrire dans _node.js_:

> npm install remark-git-contributors

Puis, ouvrir le readme.md et écrire dedans le titre **## Contributors**
Ensuite il nous faudra avoir un module par exemple readme.js dans lequel il y aura le code ci-dessous:


> import {read} from 'to-vfile'
> import {remark} from 'remark'
> import remarkGfm from 'remark-gfm'
> import remarkGitContributors from 'remark-git-contributors'
> 
> main()
> 
> async function main() {
> const file = await remark()
> .use(remarkGfm) // Required: add support for tables (a GFM feature).
> .use(remarkGitContributors)
> .process(await read('readme.md'))
> 
> console.log(String(file))
> }

Enfin il faut exécuter node readme.js et il y aura un tableau avec la liste de tous les contributeurs :) .

**Comment by Harrylepap** [comment]
ca marche ?
